groups:
- name: stable
  jobs:
  - elm-platform-0.16
  - elm-format
  - elm-format-rc
- name: master
  jobs:
  - elm-platform-master
- name: 0.17
  jobs:
  - elm-platform-0.17
- name: PRs
  jobs:
  - elm-format-pr

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: elm-platform-ci
  type: git
  source:
    uri: https://github.com/avh4/elm-platform-ci.git
    branch: master
- name: elm-format
  type: git
  source:
    uri: https://github.com/avh4/elm-format.git
    branch: master
- name: elm-format-version
  type: semver
  source:
    driver: git
    uri: git@github.com:avh4/elm-format.git
    branch: version
    file: VERSION
    private_key: {{github-private-key}}
    initial_version: 0.3.0-alpha
- name: elm-compiler-0.16
  type: git
  source:
    uri: https://github.com/elm-lang/elm-compiler.git
    branch: 0.16
- name: elm-package-0.16
  type: git
  source:
    uri: https://github.com/elm-lang/elm-package.git
    branch: 0.16
- name: elm-make-0.16
  type: git
  source:
    uri: https://github.com/elm-lang/elm-make.git
    branch: 0.16
- name: elm-reactor-0.16
  type: git
  source:
    uri: https://github.com/elm-lang/elm-reactor.git
    branch: 0.16
- name: elm-repl-0.16
  type: git
  source:
    uri: https://github.com/elm-lang/elm-repl.git
    branch: 0.16
- name: elm-compiler-0.17
  type: git
  source:
    uri: https://github.com/elm-lang/elm-compiler.git
    branch: dev
- name: elm-package-0.17
  type: git
  source:
    uri: https://github.com/elm-lang/elm-package.git
    branch: master
- name: elm-make-0.17
  type: git
  source:
    uri: https://github.com/elm-lang/elm-make.git
    branch: master
- name: elm-reactor-0.17
  type: git
  source:
    uri: https://github.com/elm-lang/elm-reactor.git
    branch: 0.17
- name: elm-repl-0.17
  type: git
  source:
    uri: https://github.com/elm-lang/elm-repl.git
    branch: master
- name: elm-compiler-master
  type: git
  source:
    uri: https://github.com/elm-lang/elm-compiler.git
    branch: master
- name: elm-package-master
  type: git
  source:
    uri: https://github.com/elm-lang/elm-package.git
    branch: master
- name: elm-make-master
  type: git
  source:
    uri: https://github.com/elm-lang/elm-make.git
    branch: master
- name: elm-reactor-master
  type: git
  source:
    uri: https://github.com/elm-lang/elm-reactor.git
    branch: master
- name: elm-repl-master
  type: git
  source:
    uri: https://github.com/elm-lang/elm-repl.git
    branch: master
- name: publish-elm-format-rc
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: concourse-demo-elm-platform
    region_name: us-west-2
    versioned_file: elm-format-linux-x64
- name: elm-format-pr
  type: pull-request
  source:
    repo: avh4/elm-format
    access_token: {{github-access-token}}

jobs:
- name: elm-format
  plan:
  - get: elm-format
    trigger: true
  - aggregate:
    - task: linux
      file: elm-format/ci/build-elm-format-linux.yml
    - task: windows
      tags: [haskell-7.10.3]
      file: elm-format/ci/build-elm-format-windows.yml
- name: elm-format-rc
  serial_groups: [elm-format-version]
  plan:
  - get: elm-format
    passed: [elm-format]
    trigger: true
  - get: elm-format-version
    params: {pre: alpha-dev}
  - task: build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: haskell, tag: "7.10.3"}
      inputs:
      - name: elm-format
      outputs:
      - name: concourse-output
      run:
        path: sh
        args:
        - -exc
        - |
          cd elm-format
          cabal update
          cabal install --only-dependencies
          cabal install
          ls -R
          cp dist/build/elm-format/elm-format ../concourse-output/
  - put: publish-elm-format-rc
    params:
      file: concourse-output/elm-format
  - put: elm-format-version
    params: {file: elm-format-version/number}
- name: elm-platform-0.16
  plan:
  - get: elm-platform-ci
  - aggregate:
    - get: elm-compiler
      resource: elm-compiler-0.16
      trigger: true
    - get: elm-package
      resource: elm-package-0.16
      trigger: true
    - get: elm-make
      resource: elm-make-0.16
      trigger: true
    - get: elm-reactor
      resource: elm-reactor-0.16
      trigger: true
    - get: elm-repl
      resource: elm-repl-0.16
      trigger: true
  - task: build-elm-platform
    file: elm-platform-ci/tasks/build-elm-compiler.yml
- name: elm-platform-0.17
  plan:
  - get: elm-platform-ci
  - aggregate:
    - get: elm-compiler
      resource: elm-compiler-0.17
      trigger: true
    - get: elm-package
      resource: elm-package-0.17
      trigger: true
    - get: elm-make
      resource: elm-make-0.17
      trigger: true
    - get: elm-reactor
      resource: elm-reactor-0.17
      trigger: true
    - get: elm-repl
      resource: elm-repl-0.17
      trigger: true
  - task: build-elm-platform
    file: elm-platform-ci/tasks/build-elm-compiler.yml
- name: elm-platform-master
  plan:
  - get: elm-platform-ci
  - aggregate:
    - get: elm-compiler
      resource: elm-compiler-master
      trigger: true
    - get: elm-package
      resource: elm-package-master
      trigger: true
    - get: elm-make
      resource: elm-make-master
      trigger: true
    - get: elm-reactor
      resource: elm-reactor-master
      trigger: true
    - get: elm-repl
      resource: elm-repl-master
      trigger: true
  - task: build-elm-platform
    file: elm-platform-ci/tasks/build-elm-compiler.yml
- name: elm-format-pr
  plan:
  - get: elm-format
    resource: elm-format-pr
    trigger: true
  - put: elm-format-pr
    params:
      path: elm-format
      status: pending
  - aggregate:
    - task: linux
      file: elm-format/ci/build-elm-format-linux.yml
    - task: windows
      tags: [haskell-7.10.3]
      file: elm-format/ci/build-elm-format-windows.yml
    on_success:
      put: elm-format-pr
      params:
        path: elm-format
        status: success
    on_failure:
      put: elm-format-pr
      params:
        path: elm-format
        status: failure
