resources:
- name: elm-format-src
  type: git
  source:
    uri: https://github.com/avh4/elm-format.git
    branch: concourse
- name: elm-compiler-src
  type: git
  source:
    uri: https://github.com/elm-lang/elm-compiler.git
    branch: master

jobs:
- name: build-elm-format
  plan:
  - get: elm-format-src
    trigger: true
  - task: elm-format-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: haskell, tag: "7.10.3"}
      inputs:
      - name: elm-format-src
        path: .
      run:
        path: ./ci.sh
- name: elm-compiler
  plan:
  - get: elm-compiler-src
    trigger: true
  - task: elm-compiler-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: haskell, tag: "7.10.3"}
      inputs:
      - name: elm-compiler-src
        path: elm-compiler
      run:
        path: sh
        args:
        - -exc
        - |
          cabal update
          cabal sandbox init
          cabal sandbox add-source elm-compiler
          cabal install -j --only-dependencies --enable-tests elm-compiler
          cabal test elm-compiler
